// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBRNEuVcrO3_YaqloFMQyUQz5DjwQb73I',
    appId: '1:1018347757311:web:c203a6e00d269452eb76ca',
    messagingSenderId: '1018347757311',
    projectId: 'bussir-f7889',
    authDomain: 'bussir-f7889.firebaseapp.com',
    databaseURL: 'https://bussir-f7889-default-rtdb.firebaseio.com',
    storageBucket: 'bussir-f7889.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI0m1j2fAguXtTdzJWowLLnlQb4fKrDgg',
    appId: '1:1018347757311:android:e12dad13163139aaeb76ca',
    messagingSenderId: '1018347757311',
    projectId: 'bussir-f7889',
    databaseURL: 'https://bussir-f7889-default-rtdb.firebaseio.com',
    storageBucket: 'bussir-f7889.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRc91LNH9VsoWxw3fhHZ33PoTD6h9AdWg',
    appId: '1:1018347757311:ios:42aa1567b2db6c8deb76ca',
    messagingSenderId: '1018347757311',
    projectId: 'bussir-f7889',
    databaseURL: 'https://bussir-f7889-default-rtdb.firebaseio.com',
    storageBucket: 'bussir-f7889.firebasestorage.app',
    iosBundleId: 'com.example.bussir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRc91LNH9VsoWxw3fhHZ33PoTD6h9AdWg',
    appId: '1:1018347757311:ios:42aa1567b2db6c8deb76ca',
    messagingSenderId: '1018347757311',
    projectId: 'bussir-f7889',
    databaseURL: 'https://bussir-f7889-default-rtdb.firebaseio.com',
    storageBucket: 'bussir-f7889.firebasestorage.app',
    iosBundleId: 'com.example.bussir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBRNEuVcrO3_YaqloFMQyUQz5DjwQb73I',
    appId: '1:1018347757311:web:3e8a76dee46519eceb76ca',
    messagingSenderId: '1018347757311',
    projectId: 'bussir-f7889',
    authDomain: 'bussir-f7889.firebaseapp.com',
    databaseURL: 'https://bussir-f7889-default-rtdb.firebaseio.com',
    storageBucket: 'bussir-f7889.firebasestorage.app',
  );
}